name = "cloudflare-worker"
type = "webpack"
workers_dev = true

account_id = "8d4857c476b9ccbd2e136d988be81e8c"

[env.production]
# The ID of the domain deploying to
zone_id = "ZONE-ID"

# The route pattern your Workers application will be served at
route = "*YOUR-DOMAIN.com/*"
